### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by satyajit-ink** [kalpeshjp89/ChasNet#1]
where can i find the dataset link?

I am trying your code for a sample super resolution. I'm feeding CHW images for now, where C=3. I've also tried to give C=1 images because thermal images are usually single channel. but the model is complaining about that. so i somehow made it 3 channel, but still its not working.

visuals["SR"] comes up as

```
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]])
```

which shouldn't be the case.

where am i going wrong ?

**Comment by satyajit-ink** [comment]
nvm i figured it out, input must be normalized !

but i still need to know how do i convert a single channel thermal to 3 channel ? maybe apply a colormap ?

**Comment by kalpeshjp89** [comment]
You can use the same single channel for all channels (i.e. just repeat it
three times). Thanks for showing interest in our work. Please let me know
if you have any other questions.

**Comment by kalpeshjp89** [comment]
Please check the details about the dataset in the paper. It is publicly
available so you can easily get it.

**Comment by satyajit-ink** [comment]
thanks i got it !
